name: Extract i18n messages
on: push

permissions: write-all

jobs:
  extract-i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add timestamp
        run: date >> timestamps
      - uses: peter-evans/create-pull-request@v4
        id: cpr
        if: github.ref == 'refs/heads/main'
        with:
          committer: DocSend Bot <docsend@dropbox.com>
          author: DocSend Bot <docsend@dropbox.com>
          commit-message: '#automatic_commit extract strings'
          title: 'Extract strings for internationalization'
          body: '(Automated Pull Request)'
          labels: automated-pr
          assignees: '$GITHUB_ACTOR'
          add-paths: 'timestamps'
      - uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          github-token: ${{ secrets.MACHINE_USER_TOKEN }}
